# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fshZMOpE5HH8Nx984vwnHh5KolUofIXj
"""

# ============================================
# SISTEMA INTELIGENTE DE INVENTARIO Y TONER
# VERSION HUMANA + GRAFICAS AVANZADAS + IA
# ============================================

# 1. INSTALAR LIBRERIAS
!pip install gradio openpyxl xlsxwriter pandas numpy matplotlib plotly -q

# 2. IMPORTAR LIBRERIAS
import pandas as pd
import numpy as np
import gradio as gr
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime

# ============================================
# 3. CARGAR ARCHIVO EXCEL
# ============================================

from google.colab import files

uploaded = files.upload()

archivo = list(uploaded.keys())[0]

# ============================================
# 4. LEER HOJAS
# ============================================

entradas = pd.read_excel(
    archivo,
    sheet_name='Entradas y Salidas'
)

base_instalada = pd.read_excel(
    archivo,
    sheet_name='Base Instalada'
)

# ============================================
# 5. LIMPIEZA DE DATOS
# ============================================

entradas = entradas.dropna(subset=['Serial'])

entradas['Cantidad'] = pd.to_numeric(
    entradas['Cantidad'],
    errors='coerce'
).fillna(0)

entradas['Rendimiento Pag consumible retirado'] = pd.to_numeric(
    entradas['Rendimiento Pag consumible retirado'],
    errors='coerce'
).fillna(0)

entradas['% Cobertura Toner'] = pd.to_numeric(
    entradas['% Cobertura Toner'],
    errors='coerce'
).fillna(0)

# ============================================
# 6. CREAR IA
# ============================================

entradas['NecesitaCambio'] = np.where(
    (
        entradas['Rendimiento Pag consumible retirado'] > 7000
    ) |
    (
        entradas['% Cobertura Toner'] < 0.06
    ),
    1,
    0
)

# ============================================
# 7. FEATURES
# ============================================

X = entradas[[
    'Cantidad',
    'Rendimiento Pag consumible retirado',
    '% Cobertura Toner'
]].values

y = entradas['NecesitaCambio'].values

# ============================================
# 8. NORMALIZACION
# ============================================

media = X.mean(axis=0)
std = X.std(axis=0)

X_norm = (X - media) / std

# ============================================
# 9. AGREGAR BIAS
# ============================================

X_norm = np.hstack((
    np.ones((X_norm.shape[0], 1)),
    X_norm
))

# ============================================
# 10. PARAMETROS
# ============================================

np.random.seed(42)

theta = np.random.randn(X_norm.shape[1])

# ============================================
# 11. FUNCION SIGMOIDE
# ============================================

def sigmoid(z):

    return 1 / (1 + np.exp(-z))

# ============================================
# 12. FUNCION LOSS
# ============================================

def loss(X, y, theta):

    m = len(y)

    h = sigmoid(X @ theta)

    epsilon = 1e-5

    return -(1/m) * np.sum(
        y*np.log(h + epsilon)
        +
        (1-y)*np.log(1-h + epsilon)
    )

# ============================================
# 13. ENTRENAMIENTO IA
# ============================================

def gradient_descent(
    X,
    y,
    theta,
    lr=0.01,
    epochs=3000
):

    m = len(y)

    historial = []

    for i in range(epochs):

        h = sigmoid(X @ theta)

        gradient = (1/m) * (X.T @ (h - y))

        theta -= lr * gradient

        l = loss(X, y, theta)

        historial.append(l)

        if i % 500 == 0:

            print(f'Epoch {i} Loss: {l}')

    return theta, historial

# ============================================
# 14. ENTRENAR MODELO
# ============================================

theta, historial = gradient_descent(
    X_norm,
    y,
    theta
)

print('MODELO ENTRENADO')

# ============================================
# 15. GRAFICA ESTADISTICA ENTRENAMIENTO
# ============================================

precision = round(
    (1 - historial[-1]) * 100,
    2
)

plt.figure(figsize=(12,6))

plt.plot(historial)

plt.title(
    f'Entrenamiento IA - Precision Aproximada: {precision}%'
)

plt.xlabel('Epochs')

plt.ylabel('Loss')

plt.grid(True)

plt.show()

# ============================================
# 16. PREDICCIONES
# ============================================

def predict(X, theta):

    probs = sigmoid(X @ theta)

    clases = np.where(
        probs >= 0.5,
        'REQUIERE CAMBIO',
        'NO REQUIERE CAMBIO'
    )

    return probs, clases

# ============================================
# 17. PREDECIR IMPRESORAS
# ============================================

probs, estados = predict(
    X_norm,
    theta
)

entradas['ProbabilidadCambio'] = (
    probs * 100
).round(2)

entradas['EstadoCambio'] = estados

# ============================================
# 18. INVENTARIO FINAL
# ============================================

inventario = entradas[[
    'Serial',
    'Modelo Impresora',
    'Ciudad',
    'Cantidad',
    'Rendimiento Pag consumible retirado',
    '% Cobertura Toner',
    'ProbabilidadCambio',
    'EstadoCambio'
]].copy()

# ============================================
# 19. TOP MAS IMPRIME
# ============================================

top_mas = inventario.sort_values(
    by='Rendimiento Pag consumible retirado',
    ascending=False
).head(10)

# ============================================
# 20. TOP MENOS IMPRIME
# ============================================

top_menos = inventario.sort_values(
    by='Rendimiento Pag consumible retirado',
    ascending=True
).head(10)

# ============================================
# 21. GRAFICA TOP MAS IMPRIME
# ============================================

fig1 = px.bar(
    top_mas,
    x='Serial',
    y='Rendimiento Pag consumible retirado',
    color='Ciudad',
    title='TOP 10 IMPRESORAS QUE MAS IMPRIMEN'
)

fig1.show()

# ============================================
# 22. GRAFICA TOP MENOS IMPRIME
# ============================================

fig2 = px.bar(
    top_menos,
    x='Serial',
    y='Rendimiento Pag consumible retirado',
    color='Ciudad',
    title='TOP 10 IMPRESORAS QUE MENOS IMPRIMEN'
)

fig2.show()

# ============================================
# 23. ALERTAS AUTOMATICAS
# ============================================

alertas = inventario[
    inventario['EstadoCambio']
    ==
    'REQUIERE CAMBIO'
]

print('\nIMPRESORAS CRITICAS\n')

print(alertas[[
    'Serial',
    'Modelo Impresora',
    'Ciudad',
    'ProbabilidadCambio',
    'EstadoCambio'
]])

# ============================================
# 24. NIVELES CRITICOS
# ============================================

inventario['NivelCritico'] = np.where(
    inventario['ProbabilidadCambio'] >= 80,
    'CRITICO',
    'NORMAL'
)

# ============================================
# 25. EXPORTAR EXCEL
# ============================================

nombre_reporte = (
    f'reporte_toner_'
    f'{datetime.now().strftime("%Y%m%d_%H%M%S")}.xlsx'
)

with pd.ExcelWriter(
    nombre_reporte,
    engine='xlsxwriter'
) as writer:

    inventario.to_excel(
        writer,
        sheet_name='Inventario',
        index=False
    )

    alertas.to_excel(
        writer,
        sheet_name='Alertas',
        index=False
    )

    top_mas.to_excel(
        writer,
        sheet_name='Top Mas Imprime',
        index=False
    )

    top_menos.to_excel(
        writer,
        sheet_name='Top Menos Imprime',
        index=False
    )

print('\nREPORTE GENERADO')

# ============================================
# 26. DESCARGAR REPORTE
# ============================================

files.download(nombre_reporte)

# ============================================
# 27. SISTEMA WEB HUMANO
# ============================================

def sistema_toner():

    tabla = inventario[[
        'Serial',
        'Modelo Impresora',
        'Ciudad',
        'ProbabilidadCambio',
        'EstadoCambio',
        'NivelCritico'
    ]]

    return tabla.fillna('NO REQUIERE CAMBIO')

# ============================================
# 28. BUSCAR IMPRESORA
# ============================================

def buscar_impresora(serial):

    resultado = inventario[
        inventario['Serial']
        .astype(str)
        .str.contains(
            serial,
            case=False,
            na=False
        )
    ]

    return resultado.fillna(
        'NO REQUIERE CAMBIO'
    )

# ============================================
# 29. DASHBOARD WEB
# ============================================

with gr.Blocks() as demo:

    gr.Markdown(
        """
        # Sistema Inteligente de Inventario y Predicción de Tóner

        Plataforma IA para monitoreo de impresoras,
        análisis predictivo y alertas automáticas.
        """
    )

    gr.Dataframe(
        value=sistema_toner(),
        label='Estado General de Impresoras'
    )

    buscador = gr.Textbox(
        label='Buscar Serial'
    )

    salida = gr.Dataframe()

    buscador.change(
        fn=buscar_impresora,
        inputs=buscador,
        outputs=salida
    )

# ============================================
# 30. EJECUTAR WEB
# ============================================

demo.launch(share=True)